/* This file is autogenerated, do not edit*/
#include "choca_automoc.dir/moc_commonbehavior_VVQJKSVDTTD7BW.cpp"
#include "choca_automoc.dir/moc_genericmonitor_F5VZEYMKPI6SVF.cpp"
#include "choca_automoc.dir/moc_genericworker_GFUXL3S3XLBLZ5.cpp"
#include "choca_automoc.dir/moc_gotopointI_DXJFBUJ53JW2YP.cpp"
#include "choca_automoc.dir/moc_rcismousepicke_DS4UTAYSFIAEKT.cpp"
#include "choca_automoc.dir/moc_specificmonito_DLSZL5TUNGGYK4.cpp"
#include "choca_automoc.dir/moc_specificworker_FO64C3CW4YGLTX.cpp"
