// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `GotoPoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <GotoPoint.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompGotoPoint__GotoPoint__go_name = "go";

const ::std::string __RoboCompGotoPoint__GotoPoint__turn_name = "turn";

const ::std::string __RoboCompGotoPoint__GotoPoint__stop_name = "stop";

const ::std::string __RoboCompGotoPoint__GotoPoint__atTarget_name = "atTarget";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompGotoPoint::upCast(::IceProxy::RoboCompGotoPoint::GotoPoint* p) { return p; }

void
::IceProxy::RoboCompGotoPoint::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGotoPoint::GotoPoint>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompGotoPoint::GotoPoint;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::go(const ::std::string& __p_nodo, ::Ice::Float __p_x, ::Ice::Float __p_y, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __RoboCompGotoPoint__GotoPoint__go_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_nodo);
        __os->write(__p_x);
        __os->write(__p_y);
        __os->write(__p_alpha);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::begin_go(const ::std::string& __p_nodo, ::Ice::Float __p_x, ::Ice::Float __p_y, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGotoPoint__GotoPoint__go_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompGotoPoint__GotoPoint__go_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_nodo);
        __os->write(__p_x);
        __os->write(__p_y);
        __os->write(__p_alpha);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_go(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompGotoPoint__GotoPoint__go_name);
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::turn(::Ice::Float __p_speed, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __RoboCompGotoPoint__GotoPoint__turn_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_speed);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::begin_turn(::Ice::Float __p_speed, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGotoPoint__GotoPoint__turn_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompGotoPoint__GotoPoint__turn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_speed);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_turn(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompGotoPoint__GotoPoint__turn_name);
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::stop(const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __RoboCompGotoPoint__GotoPoint__stop_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::begin_stop(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGotoPoint__GotoPoint__stop_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompGotoPoint__GotoPoint__stop_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_stop(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompGotoPoint__GotoPoint__stop_name);
}

bool
IceProxy::RoboCompGotoPoint::GotoPoint::atTarget(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompGotoPoint__GotoPoint__atTarget_name);
    ::IceInternal::Outgoing __og(this, __RoboCompGotoPoint__GotoPoint__atTarget_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    bool __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::begin_atTarget(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompGotoPoint__GotoPoint__atTarget_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGotoPoint__GotoPoint__atTarget_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompGotoPoint__GotoPoint__atTarget_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::__begin_atTarget(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompGotoPoint::GotoPointPrx __proxy = ::RoboCompGotoPoint::GotoPointPrx::uncheckedCast(__result->getProxy());
            bool __ret;
            try
            {
                __ret = __proxy->end_atTarget(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (bool)> _response;
    };
    return begin_atTarget(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

bool
IceProxy::RoboCompGotoPoint::GotoPoint::end_atTarget(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompGotoPoint__GotoPoint__atTarget_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::RoboCompGotoPoint::GotoPoint::ice_staticId()
{
    return ::RoboCompGotoPoint::GotoPoint::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RoboCompGotoPoint::GotoPoint::__newInstance() const
{
    return new GotoPoint;
}

::Ice::Object* RoboCompGotoPoint::upCast(::RoboCompGotoPoint::GotoPoint* p) { return p; }

namespace
{
const ::std::string __RoboCompGotoPoint__GotoPoint_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGotoPoint::GotoPoint"
};

}

bool
RoboCompGotoPoint::GotoPoint::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompGotoPoint__GotoPoint_ids, __RoboCompGotoPoint__GotoPoint_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompGotoPoint::GotoPoint::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompGotoPoint__GotoPoint_ids[0], &__RoboCompGotoPoint__GotoPoint_ids[2]);
}

const ::std::string&
RoboCompGotoPoint::GotoPoint::ice_id(const ::Ice::Current&) const
{
    return __RoboCompGotoPoint__GotoPoint_ids[1];
}

const ::std::string&
RoboCompGotoPoint::GotoPoint::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompGotoPoint::GotoPoint";
    return typeId;
#else
    return __RoboCompGotoPoint__GotoPoint_ids[1];
#endif
}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::___go(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string __p_nodo;
    ::Ice::Float __p_x;
    ::Ice::Float __p_y;
    ::Ice::Float __p_alpha;
    __is->read(__p_nodo);
    __is->read(__p_x);
    __is->read(__p_y);
    __is->read(__p_alpha);
    __inS.endReadParams();
    go(__p_nodo, __p_x, __p_y, __p_alpha, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::___turn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Float __p_speed;
    __is->read(__p_speed);
    __inS.endReadParams();
    turn(__p_speed, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::___stop(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    stop(__current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::___atTarget(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    bool __ret = atTarget(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompGotoPoint__GotoPoint_all[] =
{
    "atTarget",
    "go",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "stop",
    "turn"
};

}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompGotoPoint__GotoPoint_all, __RoboCompGotoPoint__GotoPoint_all + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompGotoPoint__GotoPoint_all)
    {
        case 0:
        {
            return ___atTarget(in, current);
        }
        case 1:
        {
            return ___go(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
        case 6:
        {
            return ___stop(in, current);
        }
        case 7:
        {
            return ___turn(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompGotoPoint::GotoPoint::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompGotoPoint::GotoPoint::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompGotoPoint::__patch(GotoPointPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompGotoPoint::GotoPointPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompGotoPoint::GotoPoint::ice_staticId(), v);
    }
}
